Repository maca-11/gitremote2, pull requests merged in 2024-11, with the labels that each got.

#5 D.pyの作成
  D.py
Labels: 緊急

#6 A.pyの作成
  A.py
Labels: 頑張って

#8 C.pyを追加#3
  c.py
Labels: 緊急, 頑張って, 開始前
